CREATE TABLE dbo.OrderItem
(
    OrderItemId int IDENTITY(1, 1) NOT NULL,
    OrderId nvarchar(10) NOT NULL,
    CatalogueItemId nvarchar(14) NOT NULL,
    CatalogueItemTypeId int NOT NULL,
    CatalogueItemName nvarchar(255) NOT NULL,
    OdsCode nvarchar(8) NULL,
    ProvisioningTypeId int NOT NULL,
    CataloguePriceTypeId int NOT NULL,
    PricingUnitTierName nvarchar(20) NULL,
    PricingUnitDescription nvarchar(35) NOT NULL,
    TimeUnitId int NULL,
    CurrencyCode nvarchar(3) NOT NULL,
    Quantity int NOT NULL,
    EstimationPeriodId int NULL,
    DeliveryDate date NULL,
    Price decimal(18, 3) NULL,
    Created datetime2 CONSTRAINT DF_OrderItem_Created DEFAULT GETUTCDATE() NOT NULL,
    LastUpdated datetime2 CONSTRAINT DF_OrderItem_LastUpdated DEFAULT GETUTCDATE() NOT NULL,
    CONSTRAINT PK_OrderItem PRIMARY KEY (OrderItemId),
    CONSTRAINT FK_OrderItem_Order_OrderId FOREIGN KEY (OrderId) REFERENCES dbo.[Order](OrderId),
    CONSTRAINT FK_OrderItem_CatalogueItemType_CatalogueItemTypeId FOREIGN KEY (CatalogueItemTypeId) REFERENCES dbo.CatalogueItemType(CatalogueItemTypeId),
    CONSTRAINT FK_OrderItem_ProvisioningType_ProvisioningTypeId FOREIGN KEY (ProvisioningTypeId) REFERENCES dbo.ProvisioningType(ProvisioningTypeId),
    CONSTRAINT FK_OrderItem_CataloguePriceType_CataloguePriceTypeId FOREIGN KEY (CataloguePriceTypeId) REFERENCES dbo.CataloguePriceType(CataloguePriceTypeId),
    CONSTRAINT FK_OrderItem_TimeUnit_TimeUnitId FOREIGN KEY (TimeUnitId) REFERENCES dbo.TimeUnit(TimeUnitId),
    CONSTRAINT FK_OrderItem_TimeUnit_EstimationPeriodId FOREIGN KEY (EstimationPeriodId) REFERENCES dbo.TimeUnit(TimeUnitId),
    CONSTRAINT FK_OrderItem_ServiceRecipient_OdsCode FOREIGN KEY (OrderId, OdsCode) REFERENCES dbo.ServiceRecipient(OrderId, OdsCode)
);
