CREATE TABLE dbo.OrderItem
(
    OrderId int NOT NULL,
    CatalogueItemId nvarchar(14) NOT NULL,
    ProvisioningTypeId int NOT NULL,
    CataloguePriceTypeId int NOT NULL,
    PricingUnitName nvarchar(20) NOT NULL,
    TimeUnitId int NULL,
    EstimationPeriodId int NULL,
    CurrencyCode nvarchar(3) NOT NULL,
    Price decimal(18, 4) NULL CONSTRAINT OrderItem_PositivePrice CHECK (Price >= 0.00),
    DefaultDeliveryDate date NULL,
    Created datetime2 CONSTRAINT DF_OrderItem_Created DEFAULT GETUTCDATE() NOT NULL,
    LastUpdated datetime2 CONSTRAINT DF_OrderItem_LastUpdated DEFAULT GETUTCDATE() NOT NULL CONSTRAINT OrderItem_LastUpdatedNotBeforeCreated CHECK (LastUpdated >= Created),
    CONSTRAINT PK_OrderItem PRIMARY KEY (OrderId, CatalogueItemId),
    CONSTRAINT FK_OrderItem_Order FOREIGN KEY (OrderId) REFERENCES dbo.[Order] (Id) ON DELETE CASCADE,
    CONSTRAINT FK_OrderItem_CatalogueItem FOREIGN KEY (CatalogueItemId) REFERENCES dbo.CatalogueItem (Id),
    CONSTRAINT FK_OrderItem_ProvisioningType FOREIGN KEY (ProvisioningTypeId) REFERENCES dbo.ProvisioningType (Id),
    CONSTRAINT FK_OrderItem_PricingUnit FOREIGN KEY (PricingUnitName) REFERENCES dbo.PricingUnit ([Name]),
    CONSTRAINT FK_OrderItem_CataloguePriceType FOREIGN KEY (CataloguePriceTypeId) REFERENCES dbo.CataloguePriceType (Id),
    CONSTRAINT FK_OrderItem_TimeUnit FOREIGN KEY (TimeUnitId) REFERENCES dbo.TimeUnit (Id),
    CONSTRAINT FK_OrderItem_EstimationPeriod FOREIGN KEY (EstimationPeriodId) REFERENCES dbo.TimeUnit (Id),
);
