CREATE USER [NHSD-ORDAPI]
	FOR LOGIN [NHSD-ORDAPI]
	WITH DEFAULT_SCHEMA = dbo;
GO

GRANT CONNECT TO [NHSD-ORDAPI];
GO

ALTER ROLE db_datareader
ADD MEMBER [NHSD-ORDAPI];
GO

ALTER ROLE db_datawriter
ADD MEMBER [NHSD-ORDAPI];
GO
